version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      cache_from:
        - rag-api:latest
    image: rag-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=False
    volumes:
      - rag_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-network

  # SvelteKit Frontend (Production)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      cache_from:
        - rag-frontend:latest
    image: rag-frontend:latest
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - PUBLIC_API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  rag_data:
    driver: local
